### ISSUE TITLE
Feature request: support for teammates under subusers

### ISSUE THREAD

**Issue by tun0** [kenzo0107/terraform-provider-sendgrid#23]
Seeing support for both teammates and subusers got me all excited. If it were also possible to manage teammates within subusers, it would make me very happy camper.

**Comment by mpg-kenzo-tanaka** [comment]
@tun0 

I apologize for the delayed response.

By specifying subusers within the provider block as shown below, 
you can manage teammates for each subuser individually.

```
provider "sendgrid" {
  subuser = "<subuser name>"
}
```

**Comment by tun0** [comment]
Awesome! Wonder how I missed that :facepalm: Actually playing around with this provider is yet another thing to add to my ever-growing to-do list :joy:

**Comment by kenzo0107** [comment]
Fix: https://github.com/kenzo0107/terraform-provider-sendgrid/commit/a0433c921a6e6779fc6f6d8749c29414790f5c78
