### ISSUE TITLE
Fix doc for SENDGRID_API_KEY

### ISSUE THREAD

**Issue by snemetz** [kenzo0107/terraform-provider-sendgrid#30]
Places that should refer to SENDGRID_API_KEY currently say SENDGRID_SUBUSER 
Had to look at source code to find correct environment variable name

**Comment by mpg-kenzo-tanaka** [comment]
@snemetz 
Thank you, I will fix it 🚀

**Comment by kenzo0107** [comment]
Fixed by https://github.com/kenzo0107/terraform-provider-sendgrid/pull/32
