### ISSUE TITLE
Teammate invite with SSO

### ISSUE THREAD

**Issue by zonArt** [kenzo0107/terraform-provider-sendgrid#79]
Would it be possible to add a parameter in sendgrid_teammate resource for SSO instead of username password ? Maybe it won't even be an invite but directly creating the teammate as SSO.

Thanks a lot

**Comment by kenzo0107** [comment]
https://github.com/kenzo0107/sendgrid/pull/44

**Comment by eekkristo** [comment]
Are there any plans to publish the new features to terraform registry? Currently looks like latest bump was done 6 months ago

**Comment by mpg-kenzo-tanaka** [comment]
@eekkristo Thank you for your question! I am actively working on plans to publish the new features to the Terraform Registry. While I can't provide an exact timeline at the moment, please rest assured that it's on our radar, and I am aiming to update it soon. I appreciate your patience and support!

**Comment by zonArt** [comment]
Very good news, thanks for your work

**Comment by kenzo0107** [comment]
@zonArt cc: @eekkristo 
support [SSO teammate](https://registry.terraform.io/providers/kenzo0107/sendgrid/latest/docs/resources/sso_teammate) by v1.3.0 : https://github.com/kenzo0107/terraform-provider-sendgrid/pull/80

> Would it be possible to add a parameter in sendgrid_teammate resource for SSO instead of username password ? Maybe it won't even be an invite but directly creating the teammate as SSO.

I considered allowing the transition from a password teammate to an SSO teammate using a parameter such as is_sso. However, this approach would complicate the code and make it harder to maintain. Additionally, the handling of certain parameters differs between the two resources  - sendgrid_teammate, sendgrid_sso_teammate: for instance, the first_name and last_name parameters are mandatory for SSO teammates but cannot be specified for password teammates.

For these reasons, I decided to implement SSO teammates as a separate resource.

**Comment by zonArt** [comment]
That's a very good idea yes, thanks a lot for everything, this new resource is exactly what I was looking for and I'm happy you implemented it, thanks again
